#!/usr/bin/env bash
# Builds supabase/upgrade-existing-project.sql: every migration after the first two, in order, as ONE transaction.
# For projects created by an older version of the app (they already have 0001_initial and create_family_members).
# Paste the file into Supabase → SQL Editor → Run. If any statement fails, nothing is changed.
set -euo pipefail
cd "$(dirname "$0")/../supabase"
{
  echo "-- Genesis Heritage Pro: upgrade an existing Supabase project to the current schema."
  echo "-- Generated by scripts/build-upgrade-sql.sh from supabase/migrations. Do not edit by hand."
  echo "-- Paste into Supabase → SQL Editor and press Run. Runs as one transaction: all or nothing."
  echo "-- Adds tables, columns, functions and access rules. Deletes no tables and no rows."
  echo "begin;"
  for f in $(ls migrations/*.sql | sort | grep -v -e 0001_initial -e 20240701_create_family_members -e 20250701000900_close_legacy_open_access); do
    echo; echo "-- ===== $(basename "$f") ====="; cat "$f"; echo
  done
  echo "commit;"
} > upgrade-existing-project.sql
{
  echo "-- Genesis Heritage Pro: privacy fix for projects created by an older version of the app."
  echo "-- Generated by scripts/build-upgrade-sql.sh. Run AFTER upgrade-existing-project.sql."
  echo "begin;"; cat migrations/20250701000900_close_legacy_open_access.sql; echo "commit;"
} > privacy-fix-existing-project.sql
echo "wrote supabase/upgrade-existing-project.sql ($(wc -c < upgrade-existing-project.sql) bytes)"
