import { describe, expect, it } from 'vitest';
import { analyzeRawDNA } from '../dna';

const twentyThree = `# This data file generated by 23andMe at: Mon Jan 01 2024
# We are using reference human assembly build 37 (also known as Annotation Release 104).
# rsid	chromosome	position	genotype
rs4477212	1	82154	AA
rs3094315	1	752566	AG
rs3131972	1	752721	--
i713426	X	2700157	G
rs2032597	Y	14366036	C
i4000690	MT	146	T
`;

const ancestry = `#AncestryDNA raw data download
#Genetic data is provided below as five TAB delimited columns.
rsid	chromosome	position	allele1	allele2
rs3131972	1	752721	A	G
rs114525117	1	759036	G	G
rs4475691	23	846808	C	T
rs11240777	26	798959	0	0
`;

const ftdna = `RSID,CHROMOSOME,POSITION,RESULT
"rs4477212","1","82154","AA"
"rs3094315","1","752566","AG"
"rs3131972","2","752721","--"
`;

describe('analyzeRawDNA', () => {
  it('reads 23andMe files', () => {
    const r = analyzeRawDNA(twentyThree, 'genome.txt');
    expect(r.format).toBe('23andMe');
    expect(r.build).toBe('GRCh37');
    expect(r.totalMarkers).toBe(6);
    expect(r.calledMarkers).toBe(5);
    expect(r.autosomalHeterozygosity).toBeCloseTo(0.5); // AA, AG
    expect(r.yMarkersCalled).toBe(1);
    expect(r.mtMarkersCalled).toBe(1);
    expect(r.perChromosome).toEqual({ '1': 3, X: 1, Y: 1, MT: 1 });
  });

  it('reads AncestryDNA two-allele files and numeric chromosomes', () => {
    const r = analyzeRawDNA(ancestry, 'AncestryDNA.txt');
    expect(r.format).toBe('AncestryDNA');
    expect(r.totalMarkers).toBe(4);
    expect(r.calledMarkers).toBe(3); // 0/0 is a no-call
    expect(r.perChromosome).toEqual({ '1': 2, X: 1, MT: 1 });
    expect(r.autosomalHeterozygosity).toBeCloseTo(0.5);
  });

  it('reads FamilyTreeDNA CSV files', () => {
    const r = analyzeRawDNA(ftdna, 'ftdna.csv');
    expect(r.format).toContain('FamilyTreeDNA');
    expect(r.totalMarkers).toBe(3);
    expect(r.callRate).toBeCloseTo(2 / 3);
  });

  it('rejects files with no genotype data', () => {
    expect(() => analyzeRawDNA('hello\nworld', 'notes.txt')).toThrow(/No genotype data/);
  });
});
